name: Mypy

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  mypy:
    name: Mypy type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install mypy aiohttp
      - run: mypy custom_components/ztm_warsaw --ignore-missing-imports
